name: 'rinha2-jonathanperis-xgh-bora-dale-python'

services:

  webapi1-python: &webapi1
    image: jonathanperis/rinha2-back-end-bora-dale-xgh-python:latest
    hostname: webapi1-python
    container_name: webapi-1-python
    depends_on:
      db:
        condition: service_healthy
    restart: always      
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/rinha?sslmode=disable"
    ports:
      - "8081:8080"    
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  webapi2-python:
    <<: *webapi1
    hostname: webapi2-python
    container_name: webapi-2-python
    ports:
      - "8082:8080"

  db:
    image: postgres
    hostname: db
    container_name: db-rinha
    restart: always
    volumes:
      - ./conf/rinha.dump.sql:/docker-entrypoint-initdb.d/rinha.dump.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "330MB"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0

  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx-rinha
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1-python
      - webapi2-python
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  k6:
    image: grafana/k6
    container_name: k6
    user: root
    environment:
      - BASE_URL=http://nginx:9999
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_EXPORT=./reports/stress-test-report.html
    volumes:
      - "./conf/stress-test:/app"
      - "./conf/stress-test/reports:/app/reports"
    working_dir: /app
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    entrypoint: ["/bin/sh", "/app/run-rinha-test.sh"]
    ports:
      - "5665:5665"